name: cicd
on:
   push:
      branches: [ "main" ]
   pull_request:
      branches: [ "main" ]
      
jobs:
   build_job:
      strategy:
        matrix:
          os: [ ubuntu-latest, windows-latest ]
      runs-on: ${{ matrix.os }}
      
      steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            submodules: true

        - name: configure
          run: cmake -S . -B build -DBUILD_TESTING=ON

        - name: build
          run: |
            cmake --build build -j $(nproc)

        - name: test
          run: |
            ctest -VV --test-dir build/tests